### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by clacladev** [mabraithwaite/nft-rarity#1]
This is a good idea. 

Can you give an example in the README on the following?
1. how to download the data/properties of an NFT collection (based on a collection address)
2. how to run the RARITY analysis on the downloaded data

Thanks a lot!!

**Comment by mabraithwaite** [comment]
Hey, sorry for late response. Initially I was just getting the metadata from projects directly (via discord and such) or by writing a script to scrape their website. I've added the ability to pull project data from https://blockfrost.io/ by using the policyId added to a strategy. Makes it easier to add a strategy for a new project and have the data auto-download. Added a couple examples to the README.

**Comment by ccarnino** [comment]
Thanks!
